language: r
cache: packages
sudo: required
warnings_are_errors: false

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
      - libgsl0ldbl
    update: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-latex-base

r_packages:
  - covr

r:
  - release
  - devel
 
after_success:
  - R CMD INSTALL .
  - Rscript -e 'library(covr); codecov()'

