language: r
cache: packages
sudo: required
warnings_are_errors: false

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
    update: true


r_packages:
  - covr

r:
  - release
  - devel
 
after_success:
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
